apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
data:
  APP_VERSION: 0.0.1-rc.1
  BACKSTAGEDB_HOST: postgres 
  BACKSTAGEDB_PORT: "5432"
  DEP_IDP_BASE_URL: http://localhost:8080
  DEP_ORG: altimetrik-digital-enablement-demo-hub
