kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080 # Expose port 80 of the ingress controller to port 8080 on your host
        protocol: TCP
      - containerPort: 443
        hostPort: 8443 # Expose port 443 of the ingress controller to port 8443 on your host
        protocol: TCP
