apiVersion: v1
kind: ServiceAccount
metadata:
  name:  headlamp-admin
  namespace: headlamp  # Or your desired namespace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  headlamp-admin-binding
subjects:
  - kind: ServiceAccount
    name:  headlamp-admin
    namespace: headlamp  # Or your desired namespace
roleRef:
  kind: ClusterRole
  name:  cluster-admin
  apiGroup: rbac.authorization.k8s.io
