apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      serviceAccountName: postgres-sa
      containers:
      - name: postgres
        image: postgres:17
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2048m"
          requests:
            memory: "512Mi"
            cpu: "1024m"
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-secrets
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
